/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Classes.GraficarProceso;
import Classes.Simulator;
import java.awt.BorderLayout;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Juan
 */
public class MainView extends javax.swing.JFrame {
    private int xMouse;
    private int yMouse;    
    private Simulator simulator;
    private SimulationView simView;
    
    
    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        String[] settings = loadSettings();
        if(settings[0].isBlank()){
            this.simulator = new Simulator(3, 1000, 1);  
        }
        else{
            this.simulator = new Simulator(Integer.parseInt(settings[0]), Integer.parseInt(settings[1]), Integer.parseInt(settings[2]));              
        }
        this.simView = new SimulationView(this.simulator);
        this.setVisible(true);
        initView();                
    }
            
    
    private String[] loadSettings(){
        String filePath = "src" + File.separator + "Config" + File.separator + "config.txt";
        
        BufferedReader bufferedReader = null;
        try {
            bufferedReader = new BufferedReader(new FileReader(new File(filePath)));
            try {
                String settings = "";
                String line;
                while ((line = bufferedReader.readLine()) != null) {                      
                    settings = line;                    
                }
                return settings.split("-");
            } catch (IOException ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                bufferedReader.close();
            } catch (IOException ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return null;
    }
        
    
    
    private void initView(){
        buttonGroup.add(createProcessButton);
        buttonGroup.add(settingsButton);
        buttonGroup.add(SimulationButton);
        
        SimulationButton.setSelected(true);
        
          
        simView.setSize(970, 510);
        simView.setLocation(0, 0);
        bodyPanel.removeAll();        
        bodyPanel.add(simView, BorderLayout.CENTER);
        bodyPanel.revalidate();
        bodyPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        closeButton = new javax.swing.JPanel();
        closeLabel = new javax.swing.JLabel();
        minimizeButton = new javax.swing.JPanel();
        minimizeLabel = new javax.swing.JLabel();
        leftPanel = new javax.swing.JPanel();
        createProcessButton = new javax.swing.JToggleButton();
        pauseButton = new javax.swing.JButton();
        finishButton = new javax.swing.JButton();
        startButton = new javax.swing.JButton();
        settingsButton = new javax.swing.JToggleButton();
        SimulationButton = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        bodyPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topPanel.setBackground(new java.awt.Color(255, 255, 255));
        topPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                topPanelMouseDragged(evt);
            }
        });
        topPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topPanelMousePressed(evt);
            }
        });
        topPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeButton.setBackground(new java.awt.Color(255, 255, 255));
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeButtonMouseExited(evt);
            }
        });
        closeButton.setLayout(new java.awt.GridBagLayout());

        closeLabel.setText("x");
        closeButton.add(closeLabel, new java.awt.GridBagConstraints());

        topPanel.add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, 30, 30));

        minimizeButton.setBackground(new java.awt.Color(255, 255, 255));
        minimizeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeButtonMouseExited(evt);
            }
        });
        minimizeButton.setLayout(new java.awt.GridBagLayout());

        minimizeLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        minimizeLabel.setText("-");
        minimizeButton.add(minimizeLabel, new java.awt.GridBagConstraints());

        topPanel.add(minimizeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, 30, 30));

        jPanel1.add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 30));

        leftPanel.setBackground(new java.awt.Color(204, 204, 204));
        leftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createProcessButton.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        createProcessButton.setText("Crear Proceso");
        createProcessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createProcessButtonActionPerformed(evt);
            }
        });
        leftPanel.add(createProcessButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 100, 50));

        pauseButton.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        pauseButton.setText("Parar");
        pauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseButtonActionPerformed(evt);
            }
        });
        leftPanel.add(pauseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 80, -1));

        finishButton.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        finishButton.setText("Reiniciar");
        leftPanel.add(finishButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 80, -1));

        startButton.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        startButton.setText("Iniciar ");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        leftPanel.add(startButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 80, -1));

        settingsButton.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        settingsButton.setText("Configuracion");
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });
        leftPanel.add(settingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 100, 50));

        SimulationButton.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        SimulationButton.setText("Simulacion");
        SimulationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimulationButtonActionPerformed(evt);
            }
        });
        leftPanel.add(SimulationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 50));

        jButton1.setText("Ver Grafico");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        leftPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, 20));

        jPanel1.add(leftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 510));

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        jPanel1.add(bodyPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 970, 510));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseEntered
        closeButton.setBackground(Color.red);
        closeLabel.setForeground(Color.white);
    }//GEN-LAST:event_closeButtonMouseEntered

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked
        this.dispose();
        closeButton.setBackground(Color.white);
        closeLabel.setForeground(Color.black);
    }//GEN-LAST:event_closeButtonMouseClicked

    private void closeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseExited
        closeButton.setBackground(Color.white);
        closeLabel.setForeground(Color.black);
    }//GEN-LAST:event_closeButtonMouseExited

    private void minimizeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeButtonMouseEntered
        minimizeButton.setBackground(Color.red);
        minimizeLabel.setForeground(Color.white);
    }//GEN-LAST:event_minimizeButtonMouseEntered

    private void minimizeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeButtonMouseClicked
        this.setState(JFrame.ICONIFIED);
        closeButton.setBackground(Color.white);
        closeLabel.setForeground(Color.black);
    }//GEN-LAST:event_minimizeButtonMouseClicked

    private void minimizeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeButtonMouseExited
        minimizeButton.setBackground(Color.white);
        minimizeLabel.setForeground(Color.black);
    }//GEN-LAST:event_minimizeButtonMouseExited

    private void topPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topPanelMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_topPanelMousePressed

    private void topPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topPanelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_topPanelMouseDragged

    private void createProcessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createProcessButtonActionPerformed
        CreateProcessView createProcessView = new CreateProcessView(simulator, this.simView);
        createProcessView.setSize(970, 510);
        createProcessView.setLocation(0, 0);
        
        bodyPanel.removeAll();
        bodyPanel.add(createProcessView, BorderLayout.CENTER);
        bodyPanel.revalidate();
        bodyPanel.repaint();
    }//GEN-LAST:event_createProcessButtonActionPerformed

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        SettingsView settingsView = new SettingsView(simulator, simView, Integer.toString(simulator.getNumCPUenable()),
                Integer.toString(simulator.getInterval()), Integer.toString(simulator.getTicksPerInstruction()));
        settingsView.setSize(970, 510);
        settingsView.setLocation(0, 0);
        
        bodyPanel.removeAll();
        bodyPanel.add(settingsView, BorderLayout.CENTER);
        bodyPanel.revalidate();
        bodyPanel.repaint();
    }//GEN-LAST:event_settingsButtonActionPerformed

    private void SimulationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimulationButtonActionPerformed
        simView.setSize(970, 510);
        simView.setLocation(0, 0);
        
        bodyPanel.removeAll();
        bodyPanel.add(simView, BorderLayout.CENTER);
        bodyPanel.revalidate();
        bodyPanel.repaint();
    }//GEN-LAST:event_SimulationButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        startButton.setText("Resumir");
        simulator.startSimulation();                    
        startButton.setEnabled(false);            
    }//GEN-LAST:event_startButtonActionPerformed

    private void pauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseButtonActionPerformed
        simulator.stopSimulation();
        startButton.setEnabled(true);
    }//GEN-LAST:event_pauseButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        GraficarProceso.RecibirCPUArray(simulator.getCPUarray() );
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton SimulationButton;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JPanel closeButton;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JToggleButton createProcessButton;
    private javax.swing.JButton finishButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel minimizeButton;
    private javax.swing.JLabel minimizeLabel;
    private javax.swing.JButton pauseButton;
    private javax.swing.JToggleButton settingsButton;
    private javax.swing.JButton startButton;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
